 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: api-gateway
   namespace: shop
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: api-gateway
     spec:
       containers:
         - name: api-gateway
           image: node:6-alpine
           command: ["/bin/sh"]
           args: ["-c", "cd /home/node;apk update && apk add ca-certificates && update-ca-certificates && apk add wget;wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/EvgenyKhaliper/nodejs-microservices-demo/master/api-gateway/app.js;wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/EvgenyKhaliper/nodejs-microservices-demo/master/api-gateway/package.json;npm install;node app.js payment-service.shop:3001 order-service.shop:3002;"]
           ports:
             - containerPort: 3000