 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: db
   namespace: shop
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: db
     spec:
       containers:
         - name: db
           image: node:6-alpine
           command: ["/bin/sh"]
           args: ["-c", "cd /home/node;apk update && apk add ca-certificates && update-ca-certificates && apk add wget;wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/EvgenyKhaliper/nodejs-microservices-demo/master/db/app.js;wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/EvgenyKhaliper/nodejs-microservices-demo/master/db/package.json;npm install;node app.js;"]
           ports:
             - containerPort: 3004