 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: payment-service
   namespace: shop
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: payment-service
     spec:
       containers:
         - name: payment-service
           image: node:6-alpine
           command: ["/bin/sh"]
           args: ["-c", "cd /home/node;apk update && apk add ca-certificates && update-ca-certificates && apk add wget;wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/EvgenyKhaliper/nodejs-microservices-demo/master/payment-service/app.js;wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/EvgenyKhaliper/nodejs-microservices-demo/master/payment-service/package.json;npm install;node app.js db.shop:3004;"]
           ports:
             - containerPort: 3001